### ISSUE TITLE
Test mappa eventi Open Data Day 

### ISSUE THREAD

**Issue by chiaracio** [AScuolaDiOpencoesione/ASOC-Blog#6]
Implementare un export dedicato del csv dati degli eventi (i dati del 3.2), con questi campi:
    - titolo evento
    - data evento
    - ora evento
    - indirizzo evento
    - nomi dei team, separati da virgole, con formato: NOME_TEAM:NOME_SCUOLA:COMUNE

I test sul modulo 3.2 vanno fatti con più scuole che partecipano a un solo evento (usando il flag apposito)

Facciamo un test della mappa su cartodb con POI e popup informativi.
Proposta: Abbonamento free su CARTO (max 75.000 visualizzazioni)

Dal 25 Febbraio al 12 Marzo aggiornare quotidianamente
Test: verificare modalità di aggiornamento dalla mappa una volta aggiornati i dati.
Test2: verificare possibilità di aggiornamento automatico (API carto?)

**Comment by sirmmo** [comment]
http://testapi.ascuoladiopencoesione.it/geocsv

**Comment by sirmmo** [comment]
aggiornato

**Comment by guglielmo** [comment]
Meglio cambiare il formato del campo team, in modo da renderlo direttamente leggibile su mappa:
"NOME_TEAM" - Istituto "NOME_SCUOLA" di NOME_COMUNE (NOME_PROVINCIA)
mantenendo sempre la separazione con una virgola, quando ci sono più di un team per lo stesso evento.
Qualora ci siano più di un istituto, aggiungere una numerazione: es:
1. "The Albatross" - ISIS Europa di Pomigliano d'Arco (Napoli),
2. "AmbientiAmoCi" - Liceo De Sanctis  Galilei di Manduria (Taranto)

**Comment by guglielmo** [comment]
Altri ritocchi, per rendere l'etichetta su mappa leggibile:
- [x] I nomi degli istituti devono avere il case uguale (non alcuni maiuscoli, alcuni minuscoli)
- [x] I nomi dei team possono rimanere così come sono stati inseriti
- [x] Quando il comune è uguale alla provincia, la provincia non compare
- [x] Quando il comune è L'Aquila o La Spezia, si usa la particella _de_, al posto di _di_.
- [x] Quando il nome del team è None, si comincia direttamente con il nome dell'istituto

**Comment by guglielmo** [comment]
Se si volessero aggiungere dei link alle pagine del team nel blog, da dentro la mappa?
